/* BioTaxa service worker: offline app shell, cached data and photos. */
// The block between the markers is generated by `npm run build:sw`. Do not edit it by hand.
// @precache-start
const VERSION = 'c50bf8886511';
const PRECACHE = [
  './',
  'assets/brand/apple-touch-icon.png',
  'assets/brand/biotaxa-mark.png',
  'assets/brand/favicon-48.png',
  'assets/brand/icon-192.png',
  'assets/brand/icon-512.png',
  'assets/brand/icon-maskable-512.png',
  'css/layouts.css',
  'css/style.css',
  'index.html',
  'js/app.js',
  'js/components/cards.js',
  'js/components/common.js',
  'js/components/icons.js',
  'js/components/layout.js',
  'js/components/quiz.js',
  'js/components/richtext.js',
  'js/components/suggest.js',
  'js/config.js',
  'js/core/dom.js',
  'js/core/prefs.js',
  'js/core/router.js',
  'js/core/storage.js',
  'js/core/userdata.js',
  'js/data/featured.js',
  'js/data/glossary.js',
  'js/data/groups.js',
  'js/data/prehistoric.js',
  'js/data/species.js',
  'js/data/topics/adaptasi.js',
  'js/data/topics/ciri.js',
  'js/data/topics/ekosistem.js',
  'js/data/topics/evolusi.js',
  'js/data/topics/fotosintesis.js',
  'js/data/topics/index.js',
  'js/data/topics/keanekaragaman.js',
  'js/data/topics/klasifikasi.js',
  'js/data/topics/mikroorganisme.js',
  'js/data/topics/perkembangbiakan.js',
  'js/data/topics/pewarisan.js',
  'js/data/topics/purba.js',
  'js/data/topics/sel.js',
  'js/i18n/ui.js',
  'js/labs/food.js',
  'js/labs/lever.js',
  'js/labs/mendel.js',
  'js/labs/osmosis.js',
  'js/labs/photosynthesis.js',
  'js/labs/scale.js',
  'js/labs/selection.js',
  'js/pages/about.js',
  'js/pages/assignment.js',
  'js/pages/compare.js',
  'js/pages/explore.js',
  'js/pages/glossary.js',
  'js/pages/home.js',
  'js/pages/lab.js',
  'js/pages/learn.js',
  'js/pages/nearby.js',
  'js/pages/prehistoric.js',
  'js/pages/quiz.js',
  'js/pages/saved.js',
  'js/pages/species.js',
  'js/pages/support.js',
  'js/pages/teacher.js',
  'js/pages/tree.js',
  'js/services/api.js',
  'js/services/conservation.js',
  'js/services/map.js',
  'js/services/media.js',
  'js/services/snapshot.js',
  'js/services/speech.js',
  'manifest.webmanifest',
];
// @precache-end

const APP_CACHE = `biotaxa-app-${VERSION}`;
const RUNTIME_CACHE = 'biotaxa-runtime-v1';
const DATA_CACHE = 'biotaxa-data-v1';
const IMAGE_CACHE = 'biotaxa-images-v1';
const LIMITS = { [DATA_CACHE]: 400, [IMAGE_CACHE]: 250, [RUNTIME_CACHE]: 80 };
const DATA_HOSTS = ['api.gbif.org', 'api.inaturalist.org', 'paleobiodb.org'];
const IMAGE_HOSTS = ['inaturalist-open-data.s3.amazonaws.com', 'static.inaturalist.org'];

self.addEventListener('install', event => {
  event.waitUntil(
    caches
      .open(APP_CACHE)
      .then(cache => cache.addAll(PRECACHE.map(path => new Request(path, { cache: 'reload' }))))
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const keep = new Set([APP_CACHE, RUNTIME_CACHE, DATA_CACHE, IMAGE_CACHE]);
      for (const key of await caches.keys())
        if (key.startsWith('biotaxa-') && !keep.has(key)) await caches.delete(key);
      await self.clients.claim();
    })()
  );
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

async function trim(cacheName) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const excess = keys.length - (LIMITS[cacheName] || 200);
  for (let i = 0; i < excess; i++) await cache.delete(keys[i]);
}

function timeout(ms) {
  return new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), ms));
}

/** Try the network first; fall back to the last good response when offline or slow. */
async function networkFirst(request, cacheName, wait = 9000) {
  const cache = await caches.open(cacheName);
  try {
    const response = await Promise.race([fetch(request), timeout(wait)]);
    if (response.ok) {
      cache.put(request, response.clone()).then(() => trim(cacheName));
    }
    return response;
  } catch (error) {
    const cached = await cache.match(request);
    if (cached) return cached;
    throw error;
  }
}

/** Serve from cache immediately; refresh in the background. */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const refresh = fetch(request)
    .then(response => {
      if (response.ok) cache.put(request, response.clone()).then(() => trim(cacheName));
      return response;
    })
    .catch(() => cached);
  return cached || refresh;
}

/** Photos: cache-first, fetched with CORS so cached entries stay small. */
async function imageCacheFirst(request) {
  const cache = await caches.open(IMAGE_CACHE);
  const cached = await cache.match(request.url);
  if (cached) return cached;
  try {
    const response = await fetch(request.url, { mode: 'cors', credentials: 'omit' });
    if (response.ok) cache.put(request.url, response.clone()).then(() => trim(IMAGE_CACHE));
    return response;
  } catch {
    return fetch(request);
  }
}

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (url.origin === self.location.origin) {
    if (request.mode === 'navigate') {
      event.respondWith(networkFirst(request, APP_CACHE, 5000).catch(() => caches.match('index.html')));
      return;
    }
    // Proxy responses and the nightly API snapshot are data: fresh when online, cached for offline use.
    if (url.pathname.includes('/api/') || url.pathname.includes('/data/snapshot/')) {
      event.respondWith(networkFirst(request, DATA_CACHE));
      return;
    }
    event.respondWith(
      caches
        .match(request, { ignoreSearch: true })
        .then(hit => hit || staleWhileRevalidate(request, RUNTIME_CACHE))
    );
    return;
  }
  if (DATA_HOSTS.includes(url.hostname) || url.hostname.endsWith('.wikipedia.org')) {
    // GBIF density map tiles are images; everything else here is JSON.
    if (url.pathname.includes('/map/')) return;
    event.respondWith(networkFirst(request, DATA_CACHE));
    return;
  }
  if (IMAGE_HOSTS.includes(url.hostname)) {
    event.respondWith(imageCacheFirst(request));
  }
  // Map tiles from OpenStreetMap are not cached, following the OSM tile usage policy.
});
